### ISSUE TITLE
Unverified HTTPS request message from URLLIB3

### ISSUE THREAD

**Issue by mlinton** [deibit/cansina#6]
On making connections to improperly configured sites with certificate errors, an error is being thrown on each request:

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

Likely have to implement a handling for these errors to prevent them from being displayed.  There are other use cases for using the tool with unverified HTTPS sites.

**Comment by deibit** [comment]
Fixed. Thanks for reporting it.

**Comment by jhaddix** [comment]
hey @deibit sorry to bring this one back up, after a git pull from my last issue I now get the above errors in the output =/

Command:
```
python cansina.py -u $TARGET -p ../SecLists-master/Discovery/Web_Content/raft-large-directories-lowercase.txt -d "cannot be found" -t 50
```

Error:
```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

**Comment by deibit** [comment]
Interesting. SSL Warnings has been disabled for Python < 2.7.9 in the last commit. and by default, all requests are made with 'verify=False' which let us bypass cert verification. 

Which Python and 'requests' version are you working with?

In any case, I disable urllib3 warnings in bac0d6c7fda4b5f0bc2286321c244374481c5a2e

Regards.

**Comment by jhaddix** [comment]
It was indeed an outdated version of ``` requests ``` updated and it;s not fixed. Thanks!

**Comment by deibit** [comment]
Good to hear. Thanks Jason.
